# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_2/project_2.srcs/sources_1/bd/proc_system/ip/proc_system_ilmb_v10_0/proc_system_ilmb_v10_0.xci
# IP: The module: 'proc_system_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_2/project_2.srcs/sources_1/bd/proc_system/ip/proc_system_ilmb_v10_0/proc_system_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_2/project_2.srcs/sources_1/bd/proc_system/ip/proc_system_ilmb_v10_0/proc_system_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_2/project_2.srcs/sources_1/bd/proc_system/ip/proc_system_ilmb_v10_0/proc_system_ilmb_v10_0.xci
# IP: The module: 'proc_system_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_2/project_2.srcs/sources_1/bd/proc_system/ip/proc_system_ilmb_v10_0/proc_system_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_2/project_2.srcs/sources_1/bd/proc_system/ip/proc_system_ilmb_v10_0/proc_system_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
